# Backlight
switch:
  - platform: template
    id: backlight
    restore_mode: ALWAYS_ON
    internal: true
    turn_on_action:
      - light.turn_on: display_backlight
    turn_off_action:
      - light.turn_off: display_backlight

# Screensaver Presence Trigger (disabled for always-on kiosk behaviour)
binary_sensor:
  - platform: homeassistant
    id: presence
    entity_id: binary_sensor.presence_presence
    on_press:
      - lvgl.resume:
      - switch.turn_on: backlight

