# ESP32-P4-JC1060P470
substitutions:
  name: "Kiosk"
  friendly_name: "Hallway-Kiosk"
  room: "Hallway"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    - logger.log: "WiFi connected, refreshing Frigate snapshots"
    - component.update: online_img_cam_1
    - component.update: online_img_cam_2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
ap:
  ssid: "${device_wifi_name} Hotspot"
  password: !secret wifi_ap_password

# Packages
packages:
  setup:
    url: https://github.com/regnighc/esphome-lvgl
    ref: Gem1
    file: guition-esp32-p4-jc1060p470/package.yaml
    refresh: 10s
