
################################################################################
# Text Sensors
################################################################################
text_sensor:
  - platform: homeassistant
    id: ${device_internal_name}_lg_state
    entity_id: media_player.lg_webos_smart_tv
    attribute: source
    on_value:
      then:
        - logger.log:
            format: "LG state: %s"
            args: [ 'x.c_str()' ]
        - lvgl.widget.update:
            id: btn_iplayer
            state:
              checked: !lambda return (0 == x.compare(std::string{"BBC iPlayer"}));
        - lvgl.widget.update:
            id: btn_kodi
            state:
              checked: !lambda return (0 == x.compare(std::string{"Game Console"}));

  - platform: template
    name: "Voice Assistant Status"
    id: voice_status
    update_interval: 5s
    lambda: |-
      if (id(esp32_microphone).is_running()) {
        return {"Listening"};
      } else {
        return {"Idle"};
      }


################################################################################
# Sensors
################################################################################
sensor:
  # WiFi
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    id: wifi_signal_sensor
    update_interval: 10s

  - platform: uptime
    type: seconds
    name: Uptime
    update_interval: 60s

  - platform: homeassistant
    id: sonos_volume_level
    entity_id: media_player.speakers
    attribute: volume_level
    on_value:
      then:
        - logger.log:
            format: "Sonos volume state: %f"
            args: [ x ]
        - lvgl.slider.update:
            id: slider_media_player
            value: !lambda return (x * 100);
        - lvgl.label.update:
            id: lbl_volume_percentage
            text:
              format: "%.0f%%"
              args: [ x * 100 ]

  - platform: template
    name: "Voice Assistant State"
    lambda: |-
      if (id(esp32_microphone).is_running()) {
        return 1;
      } else {
        return 0;
      }
    update_interval: 2s
            
