substitutions:
  icon_font: icon_font
  button_on_color: "0xFF8C00"
  button_text_color: "0xFFFFFF"
  button_control_color: "0x313131"
  button_height: 130px
  button_width: 200px
  padding: 16px
  radius: 8px

lvgl:
  style_definitions:
    - id: control

  theme:
    button:
      text_font: label_font
      scroll_on_focus: false
      radius: $radius
      width: $button_width
      height: $button_height
      pad_all: $padding
      shadow_width: 0
      text_color: $button_text_color
      checked:
        bg_color: $button_on_color
        text_color: $button_text_color
