
################################################################################
# Binary Sensors
################################################################################
binary_sensor:
  - platform: homeassistant
    id: ${device_internal_name}_lounge_sputnik_lights_state
    entity_id: light.lounge_dimmer
    trigger_on_initial_state: true
    on_state:
      then:
        - logger.log:
            format: "Lounge Sputnik Lights state: %d"
            args: [ 'x' ]
        - lvgl.widget.update:
            id: btn_lounge_sputnik_lights
            state:
              checked: !lambda return x;

  - platform: homeassistant
    id: ${device_internal_name}_lounge_uplights_state
    entity_id: light.lounge_uplights
    trigger_on_initial_state: true
    on_state:
      then:
        - logger.log:
            format: "Lounge Uplights state: %d"
            args: [ 'x' ]
        - lvgl.widget.update:
            id: btn_lounge_uplights
            state:
              checked: !lambda return x;

  - platform: homeassistant
    id: ${device_internal_name}_lg_power_state
    entity_id: media_player.lg_webos_smart_tv
    trigger_on_initial_state: true
    on_state:
      then:
        - logger.log:
            format: "LG Power state: %d"
            args: [ 'x' ]
        - lvgl.widget.update:
            id: btn_lg_power
            state:
              checked: !lambda return x;

  - platform: status
    name: "Status"
    id: "${device_internal_name}_status"
    icon: mdi:check-network
    entity_category: diagnostic

button:
  - platform: safe_mode
    name: "(Safe Mode)"
    icon: mdi:restart-alert
    id: safe_mode_btn
    entity_category: config

  - platform: restart
    name: "Restart"
    icon: mdi:restart
    id: restart_btn

  - platform: shutdown
    name: "Shutdown"
    icon: mdi:power-off
    id: shutdown_btn
