# Designed for guition-esp32-p4-jc1060p470
esp32:
  variant: esp32p4
  flash_size: 16MB
  cpu_frequency: 360MHZ
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: true
      disable_vfs_support_termios: false
      disable_vfs_support_select: false
      disable_vfs_support_dir: false
    sdkconfig_options:
      CONFIG_SPIRAM_XIP_FROM_PSRAM: "y"   # Stop screen flashing during OTA
      CONFIG_SDMMC_HOST_DEFAULT: "y"

# Esphome
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}

# External components
external_components:
  - source: github://p1ngb4ck/esphome@dev
    components: [audio, binary_storage, http_file_browser, nfs_client, picture_viewer, uart, usb_host, usb_uart, usb_storage, sd_storage, smb_client, storage, transcoder, video_player, webdav_server]
    refresh: 0s
  
# Secondary ESP32-C6 device for connectivity
esp32_hosted:
  variant: esp32c6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17
  active_high: true

# Video memory
psram:
  mode: hex
  speed: 200MHz

# Over the Air Updates
ota:
  platform: esphome

# Enable Home Assistant API
api:

# Enable logging
logger:

# Power management
esp_ldo:
  - channel: 3
    id: dsi_phy_enable
    voltage: 2.5V
    adjustable: True
  - channel: 4
    id: sd_card_power
    voltage: 2.7V
    adjustable: True

# Backlight
output:
  - platform: ledc
    pin: GPIO23
    id: gpio_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: Display Backlight
    icon: mdi:lightbulb-on
    id: display_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 0s
    gamma_correct: 1.0

# Touchscreen
i2c:
  - id: bus_a
    sda: GPIO07
    scl: GPIO08
    frequency: 400kHz
    sda_pullup_enabled: False
    scl_pullup_enabled: False

i2c_device:
  - id: i2cdev1
    address: 0x18
  - id: i2cdev2
    address: 0x32
  - id: i2cdev3
    address: 0x36
  - id: i2cdev4
    address: 0x40

touchscreen:
  - platform: gt911
    id: my_touchscreen
    i2c_id: bus_a
    reset_pin: GPIO22
    interrupt_pin: GPIO21
    transform:
      swap_xy: true
      mirror_x: false
      mirror_y: true

# Display
display:
  - platform: mipi_dsi
    id: my_display
    model: JC1060P470
    reset_pin:
      number: GPIO05
    rotation: 90
    update_interval: never
    auto_clear_enabled: false
    hsync_pulse_width: 20