sensor:
  - platform: homeassistant
    id: input_button_hallway_group_on
    entity_id: input_button.hallway_group_on
    internal: true
  - platform: homeassistant
    id: input_button_hallway_group_off
    entity_id: input_button.hallway_group_off
    internal: true
