############################################################################################################
# Sensors blocks
# Contains Home Assistant sensors that update various labels on the display
############################################################################################################



sensor:
  ######################################################################################################
  # Hallway Overhead Light Group
  # Brightness sensor that updates the corresponding slider on the display,
  # with a clamp filter to handle the case when the light is off and brightness attribute is missing
  ######################################################################################################
  - platform: homeassistant
    id: hallway_light_brightness
    entity_id: light.hallway_overhead_group
    attribute: brightness
    # Add this filter block to catch the missing attribute when the light is off
    filters:
      - clamp:
          min_value: 0
          max_value: 255
    on_value:
      - lvgl.slider.update:
          id: hallway_brightness_slider
          value: !lambda "return x;"


  ######################################################################################################
  # Livingroom Overhead Light
  # Brightness sensor that updates the corresponding slider on the display,
  # with a clamp filter to handle the case when the light is off and brightness attribute is missing
  ######################################################################################################
  - platform: homeassistant
    id: livingroom_light_brightness
    entity_id: light.living_room
    attribute: brightness
    # Add this filter block to catch the missing attribute when the light is off
    filters:
      - clamp:
          min_value: 0
          max_value: 255
    on_value:
      - lvgl.slider.update:
          id: livingroom_brightness_slider
          value: !lambda "return x;"

  ######################################################################################################
  # Livingroom Lamp Light
  # Brightness sensor that updates the corresponding slider on the display,
  # with a clamp filter to handle the case when the light is off and brightness attribute is missing
  ######################################################################################################
  - platform: homeassistant
    id: livingroom_lamp_brightness
    entity_id: light.livingroom_lamp
    attribute: brightness
    # Add this filter block to catch the missing attribute when the light is off
    filters:
      - clamp:
          min_value: 0
          max_value: 255
    on_value:
      - lvgl.slider.update:
          id: livingroom_lamp_brightness_slider
          value: !lambda "return x;"

  ######################################################################################################
  # Weather Temperature Forecast High and Low
  # Sensors that update the corresponding labels on the display with the high and low temperature
  # forecast from Home Assistant.
  ######################################################################################################
  - platform: homeassistant
    id: high_temp_ha
    entity_id: sensor.weather_forecast_day_0_high
    on_value:
      - lvgl.label.update:
          id: high_temp_label
          text: !lambda |-
            float v = x;
            return std::isnan(v) ? std::string("--°C") : str_sprintf("%.0f°C", v);

  - platform: homeassistant
    id: low_temp_ha
    entity_id: sensor.weather_forecast_day_0_low
    on_value:
      - lvgl.label.update:
          id: low_temp_label
          text: !lambda |-
            float v = x;
            return std::isnan(v) ? std::string("--°C") : str_sprintf("%.0f°C", v);

binary_sensor:
  ######################################################################################################
  # Hallway Lamp State
  # Binary sensor that updates the corresponding slider on the display
  ######################################################################################################
  - platform: homeassistant
    id: hall_lamp_state
    entity_id: switch.hall_lamp
    on_value:
      then:
        - lvgl.widget.update:
            id: hallway_accent_slider
            bg_color: !lambda "return x ? 0xE5CA3E : 0xFF6B6B6B;"

text_sensor:
  ############################################################################################################
  # Weather Condition
  # Updates the weather icon label on the display based on the current weather condition from Home Assistant
  ############################################################################################################
  - platform: homeassistant
    id: weather_condition
    entity_id: weather.forecast_home # Your specific entity
    on_value:
      then:
        - lvgl.label.update:
            id: weather_icon_label
            # 'x' is the state coming from HA (e.g., "sunny")
            text: !lambda |-
              if (x == "sunny") return "${weather_sunny}";
              if (x == "clear-night") return "${weather_night}";
              if (x == "cloudy") return "${weather_partly_cloudy}";
              if (x == "partlycloudy") return "${weather_partly_cloudy}";
              if (x == "rainy") return "${weather_rainy}";
              if (x == "pouring") return "${weather_pouring}";
              if (x == "snowy") return "${weather_snowy}";
              if (x == "lightning" || x == "lightning-rainy") return "${weather_partly_lightning}";
              if (x == "fog") return "${weather_windy_variant}"; // Using windy-variant as a proxy for fog
              
              // Fallback if the API returns something unexpected
              return "${weather_sunny_alert}";

  ####################################################################################################
  # Block 2 Camera 4
  # Last person detection time and "time ago" sensors, updating corresponding labels on the display
  ####################################################################################################
  - platform: homeassistant
    id: b2c4_last_person_detection
    entity_id: sensor.b2c4_last_person_detection
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_b2c4_last_person_detection
            text: !lambda return x.c_str();
  - platform: homeassistant
    id: b2c4_last_person_detection_ago
    entity_id: sensor.b2c4_last_person_detection_ago
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_b2c4_last_person_detection_ago
            text: !lambda return x.c_str();

  ####################################################################################################
  # Block 2 Camera 0
  # Last person detection time and "time ago" sensors, updating corresponding labels on the display
  ####################################################################################################
  - platform: homeassistant
    id: b2c0_last_person_detection
    entity_id: sensor.b2c0_last_person_detection
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_b2c0_last_person_detection
            text: !lambda return x.c_str();
  - platform: homeassistant
    id: b2c0_last_person_detection_ago
    entity_id: sensor.b2c0_last_person_detection_ago
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_b2c0_last_person_detection_ago
            text: !lambda return x.c_str();