# Designed for guition-esp32-p4-jc4880p443
esp32:
  variant: esp32p4
  flash_size: 16MB
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: yes

# Esphome
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}

# Secondary ESP32-C6 device for connectivity
esp32_hosted:
  active_high: true
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17

# Video memory
psram:
  speed: 200MHz

# Over the Air Updates
ota:
  platform: esphome

# Enable Home Assistant API
api:

# Enable logging
logger:

# Power management
esp_ldo:
  - channel: 3
    voltage: 2.5V

# Backlight
output:
  - platform: ledc
    id: backlight_output
    pin: GPIO23
    frequency: 100Hz
    inverted: false
    min_power: 0.0
    max_power: 0.8

light:
  - platform: monochromatic
    output: backlight_output
    name: Screen
    icon: mdi:television
    entity_category: config
    id: display_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms

# I2C
i2c:
  sda: GPIO7
  scl: GPIO8
  scan: false
  frequency: 400kHz

# Touchscreen
touchscreen:
  - platform: gt911
    id: my_touchscreen
    display: my_display

# Display
display:
  - platform: mipi_dsi
    id: my_display
    model: JC4880P443
